### ISSUE TITLE
Failed compilation Ubuntu14.04

### ISSUE THREAD

**Issue by pw31** [glinscott/leela-chess#403]
Was anybody successful with compiling lczero on Ubuntu 14.04?
I'd really love to be able to compile.  This is where I stand ...
Any help would be highly appreciated!

> git clone https://github.com/glinscott/leela-chess.git
> cd leela-chess
> git submodule update --init --recursive
> sudo apt install cmake3 libboost-all-dev libopenblas-dev opencl-headers zlib1g-dev

(I needed to change from cmake -> cmake3)
> sudo aptitude install cmake3

> mkdir build && cd build
> cmake -DFEATURE_USE_CPU_ONLY=On -DBLAS_INCLUDE_DIRS=/usr/include ..

(I needed to include explicit setting of BLAS_INCLUDE_DIRS)

SUCCESS:
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- A library with BLAS API found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pw31/chess/Engines/LCzero/leela-chess/build

> make
[  3%] Building CXX object CMakeFiles/objs.dir/src/UCIOption.cpp.o
In file included from /home/pw31/chess/Engines/LCzero/leela-chess/src/Utils.h:22:0,
                 from /home/pw31/chess/Engines/LCzero/leela-chess/src/UCIOption.cpp:22:
/home/pw31/chess/Engines/LCzero/leela-chess/src/config.h:39:50: warning: multi-character character constant [-Wmultichar]
 static constexpr int SELFCHECK_MIN_EXPANSIONS = 2'000'000;
                                                  ^
/home/pw31/chess/Engines/LCzero/leela-chess/src/config.h:39:50: error: expected ‘,’ or ‘;’ before '\x303030'
make[2]: *** [CMakeFiles/objs.dir/src/UCIOption.cpp.o] Error 1
make[1]: *** [CMakeFiles/objs.dir/all] Error 2
make: *** [all] Error 2

**Comment by maximiliano1956** [comment]
You have to compile with at least a c++ v14 compiler

**Comment by pw31** [comment]
... and how would I do this on Ubuntu 14.04, please?

**Comment by maximiliano1956** [comment]
You have to upgrade gcc compiling chain

**Comment by pw31** [comment]
Thanks. I tried commands as listed below, eventually getting a different error related to BLAS.
Any idea?  Thank you!

> sudo add-apt-repository ppa:ubuntu-toolchain-r/test
> sudo apt-get update
> sudo apt-get install gcc-5 g++-5
> sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

> rm -rf build
> mkdir build && cd build
> cmake -DFEATURE_USE_CPU_ONLY=On -DBLAS_INCLUDE_DIRS=/usr/include ..

(I needed to include explicit setting of BLAS_INCLUDE_DIRS)

-- The CXX compiler identification is GNU 5.4.1
-- The C compiler identification is GNU 5.4.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- A library with BLAS API found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pw31/chess/Engines/LCzero/leela-chess/build

> make
Scanning dependencies of target objs
[  3%] Building CXX object CMakeFiles/objs.dir/src/UCIOption.cpp.o
[  6%] Building CXX object CMakeFiles/objs.dir/src/Movegen.cpp.o
[  9%] Building CXX object CMakeFiles/objs.dir/src/UCTSearch.cpp.o
[ 12%] Building CXX object CMakeFiles/objs.dir/src/SMP.cpp.o
[ 16%] Building CXX object CMakeFiles/objs.dir/src/UCI.cpp.o
[ 19%] Building CXX object CMakeFiles/objs.dir/src/NNCache.cpp.o
[ 22%] Building CXX object CMakeFiles/objs.dir/src/Parameters.cpp.o
[ 25%] Building CXX object CMakeFiles/objs.dir/src/Position.cpp.o
[ 29%] Building CXX object CMakeFiles/objs.dir/src/Training.cpp.o
[ 32%] Building CXX object CMakeFiles/objs.dir/src/Random.cpp.o
[ 35%] Building CXX object CMakeFiles/objs.dir/src/UCTNode.cpp.o
[ 38%] Building CXX object CMakeFiles/objs.dir/src/Utils.cpp.o
[ 41%] Building CXX object CMakeFiles/objs.dir/src/pgn.cpp.o
[ 45%] Building CXX object CMakeFiles/objs.dir/src/Network.cpp.o
/home/pw31/chess/Engines/LCzero/leela-chess/src/Network.cpp: In static member function ‘static void Network::initialize()’:
/home/pw31/chess/Engines/LCzero/leela-chess/src/Network.cpp:507:55: error: ‘openblas_get_corename’ was not declared in this scope
     myprintf("BLAS Core: %s\n", openblas_get_corename());
                                                       ^
make[2]: *** [CMakeFiles/objs.dir/src/Network.cpp.o] Error 1
make[1]: *** [CMakeFiles/objs.dir/all] Error 2
make: *** [all] Error 2

**Comment by meekersX** [comment]
What version of libopenblas-dev do you have? I found that lczero would not compile with the version in the 14.04 repository.

**Comment by smatovic** [comment]
I simply removed the printf in Network.cpp and compiled via Makefile from src folder.

To build an static version (except pthread and OpenCL) i used the following mod:

diff --git a/src/Makefile b/src/Makefile
index fad0b6c..2b20f0f 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -24,13 +24,14 @@ clang:
                LDFLAGS='$(LDFLAGS) -flto -fuse-linker-plugin' \
                lczero
 
-DYNAMIC_LIBS = -lboost_program_options -lboost_system -lboost_filesystem -lpthread -lz
-LIBS =
+LIBS = -lboost_program_options -lboost_system -lboost_filesystem -lz
+DYNAMIC_LIBS = -lpthread
+#LIBS =
 
 ifeq ($(THE_OS),Linux)
 # for Linux with OpenBLAS
        CXXFLAGS += -I/usr/include/openblas
-       DYNAMIC_LIBS += -lopenblas
+       LIBS += -lopenblas
        DYNAMIC_LIBS += -lOpenCL
 endif
 ifeq ($(THE_OS),Darwin)
@@ -59,10 +60,10 @@ deps = $(sources:%.cpp=%.d)
 -include $(deps)
 
 %.o: %.cpp
-       $(CXX) $(CXXFLAGS) $(CPPFLAGS) -c -o $@ $<
+       $(CXX) $(CXXFLAGS) $(CPPFLAGS) -static-libstdc++ -c -o $@ $<
 
 lczero: $(objects)
-       $(CXX) $(LDFLAGS) -o $@ $^ $(LIBS) $(DYNAMIC_LIBS)
+       $(CXX) $(LDFLAGS) -o $@ $^ -static-libstdc++ -Wl,-Bstatic $(LIBS) -Wl,-Bdynamic $(DYNAMIC_LIBS)
 
 clean:
        -$(RM) lczero $(objects) $(deps)

**Comment by pw31** [comment]
Thanks!  After removing line 507 in src/Network.cpp I was able to compile on Ubuntu 14.04!
Cheers!
